import mongoose from 'mongoose';

const QuarterDataSchema = new mongoose.Schema({
  // Identification
  simulationCode: { type: String, default: '' },
  groupNumber: { type: Number, required: true, default: 1 },
  companyNumber: { type: Number, required: true, default: 1 },
  identityNumber: { type: String, default: '' },
  year: { type: Number, required: true },
  quarter: { type: Number, required: true, min: 1, max: 4 },
  status: { type: Number, default: 0 },
  numProducts: { type: Number, required: true, min: 1, max: 8, default: 3 },

  // ──────────────────── DECISIONS ────────────────────
  decisions: {
    majorProductImprovement: { type: [Boolean], default: [] },
    prices: {
      export: { type: [Number], default: [] },
      home: { type: [Number], default: [] },
    },
    advertising: {
      tradePress: { type: [Number], default: [] },
      pressTV: { type: [Number], default: [] },
      merchandising: { type: [Number], default: [] },
    },
    assemblyTime: { type: [Number], default: [] },
    salespeople: {
      export: { type: Number, default: 0 },
      south: { type: Number, default: 0 },
      west: { type: Number, default: 0 },
      north: { type: Number, default: 0 },
    },
    salespeopleRemuneration: {
      quarterlySalary: { type: Number, default: 0 },
      salesCommission: { type: Number, default: 0 },
    },
    assemblyWageRate: { type: Number, default: 0 },
    shiftLevel: { type: Number, default: 1, min: 1, max: 3 },
    maintenanceHours: { type: Number, default: 0 },
    deliverySchedule: {
      export: { type: [Number], default: [] },
      south: { type: [Number], default: [] },
      west: { type: [Number], default: [] },
      north: { type: [Number], default: [] },
    },
    managementBudget: { type: Number, default: 0 },
    dividendRate: { type: Number, default: 0 },
    daysCreditAllowed: { type: Number, default: 0 },
    machinesToSell: { type: Number, default: 0 },
    newMachinesToOrder: { type: Number, default: 0 },
    vansToBuy: { type: Number, default: 0 },
    vansToSell: { type: Number, default: 0 },
    infoOnCompanies: { type: Boolean, default: false },
    infoOnMarketShares: { type: Boolean, default: false },
    researchExpenditure: { type: [Number], default: [] },
    personnel: {
      salespeople: {
        recruit: { type: Number, default: 0 },
        dismiss: { type: Number, default: 0 },
        train: { type: Number, default: 0 },
      },
      assemblyWorkers: {
        recruit: { type: Number, default: 0 },
        dismiss: { type: Number, default: 0 },
        train: { type: Number, default: 0 },
      },
    },
    materials: {
      unitsToOrder: { type: Number, default: 0 },
      supplierNo: { type: Number, default: 0 },
      numDeliveries: { type: Number, default: 0 },
    },
  },

  // ──────────────────── RESULTS ────────────────────
  results: {
    machines: {
      availableLastQuarter: { type: Number, default: 0 },
      decommissioned: { type: Number, default: 0 },
      inUse: { type: Number, default: 0 },
      installed: { type: Number, default: 0 },
      availableNextQuarter: { type: Number, default: 0 },
    },
    vehicles: {
      availableLastQuarter: { type: Number, default: 0 },
    },
    assemblyHours: {
      available: { type: Number, default: 0 },
      absenteeism: { type: Number, default: 0 },
      worked: { type: Number, default: 0 },
      strikeWeeksNext: { type: Number, default: 0 },
    },
    machineHours: {
      available: { type: Number, default: 0 },
      breakdownTime: { type: Number, default: 0 },
      used: { type: Number, default: 0 },
      maintenanceHours: { type: Number, default: 0 },
      efficiency: { type: Number, default: 0 },
    },
    materials: {
      openingStock: { type: Number, default: 0 },
      delivered: { type: Number, default: 0 },
      used: { type: Number, default: 0 },
      closingStock: { type: Number, default: 0 },
      onOrder: { type: Number, default: 0 },
      availableNext: { type: Number, default: 0 },
    },
    personnel: {
      salespeople: {
        atStart: { type: Number, default: 0 },
        recruited: { type: Number, default: 0 },
        trainees: { type: Number, default: 0 },
        dismissed: { type: Number, default: 0 },
        leavers: { type: Number, default: 0 },
        availableNext: { type: Number, default: 0 },
      },
      assemblyWorkers: {
        atStart: { type: Number, default: 0 },
        recruited: { type: Number, default: 0 },
        trainees: { type: Number, default: 0 },
        dismissed: { type: Number, default: 0 },
        leavers: { type: Number, default: 0 },
        availableNext: { type: Number, default: 0 },
      },
      machinists: {
        atStart: { type: Number, default: 0 },
        recruited: { type: Number, default: 0 },
        dismissed: { type: Number, default: 0 },
        leavers: { type: Number, default: 0 },
        availableNext: { type: Number, default: 0 },
      },
    },
    productStats: {
      scheduled: { type: [Number], default: [] },
      produced: { type: [Number], default: [] },
      rejected: { type: [Number], default: [] },
      serviced: { type: [Number], default: [] },
      delivered: {
        export: { type: [Number], default: [] },
        south: { type: [Number], default: [] },
        west: { type: [Number], default: [] },
        north: { type: [Number], default: [] },
      },
      orders: {
        export: { type: [Number], default: [] },
        south: { type: [Number], default: [] },
        west: { type: [Number], default: [] },
        north: { type: [Number], default: [] },
      },
      sales: {
        export: { type: [Number], default: [] },
        south: { type: [Number], default: [] },
        west: { type: [Number], default: [] },
        north: { type: [Number], default: [] },
      },
      backlog: {
        export: { type: [Number], default: [] },
        south: { type: [Number], default: [] },
        west: { type: [Number], default: [] },
        north: { type: [Number], default: [] },
      },
      stocks: {
        export: { type: [Number], default: [] },
        south: { type: [Number], default: [] },
        west: { type: [Number], default: [] },
        north: { type: [Number], default: [] },
      },
      productImprovements: { type: [String], default: [] },
    },
    overheads: {
      advertising: { type: Number, default: 0 },
      salesForceSalary: { type: Number, default: 0 },
      salesOffice: { type: Number, default: 0 },
      guaranteeServicing: { type: Number, default: 0 },
      transportFleet: { type: Number, default: 0 },
      hiredTransport: { type: Number, default: 0 },
      productResearch: { type: Number, default: 0 },
      personnelDept: { type: Number, default: 0 },
      maintenance: { type: Number, default: 0 },
      warehousing: { type: Number, default: 0 },
      businessIntelligence: { type: Number, default: 0 },
      managementBudget: { type: Number, default: 0 },
      creditControl: { type: Number, default: 0 },
      otherMiscCosts: { type: Number, default: 0 },
      totalOverheads: { type: Number, default: 0 },
    },
    taxableProfitLoss: { type: Number, default: 0 },
    profitAndLoss: {
      salesRevenue: { type: Number, default: 0 },
      openingStockValue: { type: Number, default: 0 },
      materialsPurchased: { type: Number, default: 0 },
      assemblyWages: { type: Number, default: 0 },
      machinistsWages: { type: Number, default: 0 },
      machineRunningCosts: { type: Number, default: 0 },
      closingStockValue: { type: Number, default: 0 },
      costOfSales: { type: Number, default: 0 },
      grossProfit: { type: Number, default: 0 },
      interestReceived: { type: Number, default: 0 },
      interestPaid: { type: Number, default: 0 },
      overheads: { type: Number, default: 0 },
      depreciation: { type: Number, default: 0 },
      taxAssessed: { type: Number, default: 0 },
      netProfit: { type: Number, default: 0 },
      dividendPaid: { type: Number, default: 0 },
      transferredToReserves: { type: Number, default: 0 },
    },
    balanceSheet: {
      assets: {
        property: { type: Number, default: 0 },
        machines: { type: Number, default: 0 },
        vehicles: { type: Number, default: 0 },
        productStocks: { type: Number, default: 0 },
        materialStock: { type: Number, default: 0 },
        debtors: { type: Number, default: 0 },
        cashInvested: { type: Number, default: 0 },
      },
      liabilities: {
        taxAssessedDue: { type: Number, default: 0 },
        creditors: { type: Number, default: 0 },
        overdraft: { type: Number, default: 0 },
        unsecuredLoans: { type: Number, default: 0 },
      },
      netAssets: { type: Number, default: 0 },
      ordinaryCapital: { type: Number, default: 2000000 },
      reserves: { type: Number, default: 0 },
      totalFunding: { type: Number, default: 0 },
    },
    cashFlow: {
      tradingReceipts: { type: Number, default: 0 },
      tradingPayments: { type: Number, default: 0 },
      taxPaid: { type: Number, default: 0 },
      operatingCashFlow: { type: Number, default: 0 },
      interestReceived: { type: Number, default: 0 },
      capitalReceipts: { type: Number, default: 0 },
      capitalPayments: { type: Number, default: 0 },
      investingCashFlow: { type: Number, default: 0 },
      interestPaid: { type: Number, default: 0 },
      dividendPaid: { type: Number, default: 0 },
      financingCashFlow: { type: Number, default: 0 },
      netCashFlow: { type: Number, default: 0 },
      overdraftLimitNext: { type: Number, default: 0 },
    },
    sharePrice: { type: Number, default: 100 },
    dividendPercent: { type: Number, default: 0 },
    economic: {
      gdp: { type: Number, default: 734 },
      unemploymentRate: { type: Number, default: 5 },
      centralBankRate: { type: Number, default: 5 },
      materialPrice: { type: Number, default: 50231 },
    },
  },

  isProcessed: { type: Boolean, default: false },
  isSeedData: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now },
}, {
  timestamps: true,
});

QuarterDataSchema.index(
  { groupNumber: 1, companyNumber: 1, year: 1, quarter: 1 },
  { unique: true }
);

export default mongoose.models.QuarterData || mongoose.model('QuarterData', QuarterDataSchema);
